export type FilterTab = 'all' | 'damage' | 'stats' | 'skills'

export const FILTER_TABS: Array<{ id: FilterTab; label: string }> = [
  { id: 'all', label: 'All' },
  { id: 'damage', label: 'Damage' },
  { id: 'stats', label: 'All stats' },
  { id: 'skills', label: 'Skills' },
]

export const RESISTANCE_KEYS = [
  'fire_resistance',
  'cold_resistance',
  'lightning_resistance',
  'poison_resistance',
  'arcane_resistance',
  'all_resistances',
  'max_fire_resistance',
  'max_cold_resistance',
  'max_lightning_resistance',
  'max_poison_resistance',
  'max_arcane_resistance',
  'max_all_resistances',
  'fire_absorption',
  'cold_absorption',
  'lightning_absorption',
  'poison_absorption',
  'arcane_absorption',
]

export const RESOURCE_KEYS = [
  'life',
  'mana',
  'increased_life',
  'increased_mana',
  'life_replenish',
  'life_replenish_pct',
  'mana_replenish',
  'mana_replenish_pct',
  'life_steal',
  'life_steal_rate',
  'life_steal_instant',
  'mana_steal',
  'mana_steal_rate',
  'life_per_kill',
  'mana_per_kill',
  'mana_cost_reduction',
  'mana_cost_paid_in_life',
  'damage_recouped_as_life',
  'damage_recouped_as_mana',
  'overflow_mana_recouped_as_life',
  'damage_drained_from_mana',
  'max_life_to_mana',
  'max_mana_to_life',
  'overflow_res_to_life',
  'life_replenish_flask',
  'damage_mitigated_flask',
]

export const MITIGATION_KEYS = [
  'defense',
  'enhanced_defense',
  'defense_vs_missiles',
  'damage_reduced',
  'all_damage_taken_reduced_pct',
  'physical_damage_reduction',
  'magic_damage_reduction',
  'magic_absorption',
  'damage_taken_reduced',
  'damage_mitigation',
  'damage_return',
  'block_chance',
  'dodge_chance',
  'dodge_spell_hits',
  'suppress_spell_hits',
  'faster_hit_recovery',
  'immune_duration',
  'cc_immune_no_dodge',
  'poison_length_reduced',
  'max_colossus_stacks',
  'max_combat_mitigation_stacks',
]

export const SKILL_BONUS_KEYS = [
  'all_skills',
  'physical_skills',
  'arcane_skills',
  'cold_skills',
  'fire_skills',
  'poison_skills',
  'lightning_skills',
  'explosion_skills',
  'summon_skills',
]

export const WORLD_LOOT_KEYS = [
  'movement_speed',
  'jumping_power',
  'light_radius',
  'experience_gain',
  'magic_find',
  'gold_find',
  'merchant_prices',
  'increased_all_attributes',
]
