// Exact raster assets used by the Tauri mercenary view.
const MERC_ICONS: &[(&str, &[u8])] = &[
    (
        "merc_archer/ability_expert",
        include_bytes!("../../../assets/skills/merc_archer/ability_expert.png"),
    ),
    (
        "merc_archer/artillery_command",
        include_bytes!("../../../assets/skills/merc_archer/artillery_command.png"),
    ),
    (
        "merc_archer/aura_expert",
        include_bytes!("../../../assets/skills/merc_archer/aura_expert.png"),
    ),
    (
        "merc_archer/brainfreeze",
        include_bytes!("../../../assets/skills/merc_archer/brainfreeze.png"),
    ),
    (
        "merc_archer/burst_of_agility",
        include_bytes!("../../../assets/skills/merc_archer/burst_of_agility.png"),
    ),
    (
        "merc_archer/explosive_shot",
        include_bytes!("../../../assets/skills/merc_archer/explosive_shot.png"),
    ),
    (
        "merc_archer/hawk_eye",
        include_bytes!("../../../assets/skills/merc_archer/hawk_eye.png"),
    ),
    (
        "merc_archer/heatseeking_missile",
        include_bytes!("../../../assets/skills/merc_archer/heatseeking_missile.png"),
    ),
    (
        "merc_archer/hunters_trap",
        include_bytes!("../../../assets/skills/merc_archer/hunters_trap.png"),
    ),
    (
        "merc_archer/piercingshot",
        include_bytes!("../../../assets/skills/merc_archer/piercingshot.png"),
    ),
    (
        "merc_archer/powershot",
        include_bytes!("../../../assets/skills/merc_archer/powershot.png"),
    ),
    (
        "merc_archer/quickslugs",
        include_bytes!("../../../assets/skills/merc_archer/quickslugs.png"),
    ),
    (
        "merc_archer/rapidfire",
        include_bytes!("../../../assets/skills/merc_archer/rapidfire.png"),
    ),
    (
        "merc_archer/ravens_claw",
        include_bytes!("../../../assets/skills/merc_archer/ravens_claw.png"),
    ),
    (
        "merc_archer/shatter_armor",
        include_bytes!("../../../assets/skills/merc_archer/shatter_armor.png"),
    ),
    (
        "merc_archer/soul_funnel",
        include_bytes!("../../../assets/skills/merc_archer/soul_funnel.png"),
    ),
    (
        "merc_archer/spreadshot",
        include_bytes!("../../../assets/skills/merc_archer/spreadshot.png"),
    ),
    (
        "merc_archer/trigger_power",
        include_bytes!("../../../assets/skills/merc_archer/trigger_power.png"),
    ),
    (
        "merc_knight/aura_expert",
        include_bytes!("../../../assets/skills/merc_knight/aura_expert.png"),
    ),
    (
        "merc_knight/backlash",
        include_bytes!("../../../assets/skills/merc_knight/backlash.png"),
    ),
    (
        "merc_knight/blessed_strike",
        include_bytes!("../../../assets/skills/merc_knight/blessed_strike.png"),
    ),
    (
        "merc_knight/brutal_bash",
        include_bytes!("../../../assets/skills/merc_knight/brutal_bash.png"),
    ),
    (
        "merc_knight/charge_strike",
        include_bytes!("../../../assets/skills/merc_knight/charge_strike.png"),
    ),
    (
        "merc_knight/commanders_heart",
        include_bytes!("../../../assets/skills/merc_knight/commanders_heart.png"),
    ),
    (
        "merc_knight/defenses",
        include_bytes!("../../../assets/skills/merc_knight/defenses.png"),
    ),
    (
        "merc_knight/evasive_tactics",
        include_bytes!("../../../assets/skills/merc_knight/evasive_tactics.png"),
    ),
    (
        "merc_knight/fatal_strike",
        include_bytes!("../../../assets/skills/merc_knight/fatal_strike.png"),
    ),
    (
        "merc_knight/hulking_rage",
        include_bytes!("../../../assets/skills/merc_knight/hulking_rage.png"),
    ),
    (
        "merc_knight/plated_armor",
        include_bytes!("../../../assets/skills/merc_knight/plated_armor.png"),
    ),
    (
        "merc_knight/protecting_charge",
        include_bytes!("../../../assets/skills/merc_knight/protecting_charge.png"),
    ),
    (
        "merc_knight/spiked_armor",
        include_bytes!("../../../assets/skills/merc_knight/spiked_armor.png"),
    ),
    (
        "merc_knight/stacked_pain",
        include_bytes!("../../../assets/skills/merc_knight/stacked_pain.png"),
    ),
    (
        "merc_knight/stacked_rage",
        include_bytes!("../../../assets/skills/merc_knight/stacked_rage.png"),
    ),
    (
        "merc_knight/sword_grip",
        include_bytes!("../../../assets/skills/merc_knight/sword_grip.png"),
    ),
    (
        "merc_knight/taunt",
        include_bytes!("../../../assets/skills/merc_knight/taunt.png"),
    ),
    (
        "merc_knight/warriors_might",
        include_bytes!("../../../assets/skills/merc_knight/warriors_might.png"),
    ),
    (
        "merc_magister/arcane_apocalypse",
        include_bytes!("../../../assets/skills/merc_magister/arcane_apocalypse.png"),
    ),
    (
        "merc_magister/arcane_barrage",
        include_bytes!("../../../assets/skills/merc_magister/arcane_barrage.png"),
    ),
    (
        "merc_magister/arcane_blast",
        include_bytes!("../../../assets/skills/merc_magister/arcane_blast.png"),
    ),
    (
        "merc_magister/arcane_fire",
        include_bytes!("../../../assets/skills/merc_magister/arcane_fire.png"),
    ),
    (
        "merc_magister/arcane_link",
        include_bytes!("../../../assets/skills/merc_magister/arcane_link.png"),
    ),
    (
        "merc_magister/arcane_meteor",
        include_bytes!("../../../assets/skills/merc_magister/arcane_meteor.png"),
    ),
    (
        "merc_magister/arcane_nova",
        include_bytes!("../../../assets/skills/merc_magister/arcane_nova.png"),
    ),
    (
        "merc_magister/arcanes_blessing",
        include_bytes!("../../../assets/skills/merc_magister/arcanes_blessing.png"),
    ),
    (
        "merc_magister/aura_expert",
        include_bytes!("../../../assets/skills/merc_magister/aura_expert.png"),
    ),
    (
        "merc_magister/cosmic_bolt",
        include_bytes!("../../../assets/skills/merc_magister/cosmic_bolt.png"),
    ),
    (
        "merc_magister/elemental_intellect",
        include_bytes!("../../../assets/skills/merc_magister/elemental_intellect.png"),
    ),
    (
        "merc_magister/magic_claw",
        include_bytes!("../../../assets/skills/merc_magister/magic_claw.png"),
    ),
    (
        "merc_magister/manaflux",
        include_bytes!("../../../assets/skills/merc_magister/manaflux.png"),
    ),
    (
        "merc_magister/replenishing_touch",
        include_bytes!("../../../assets/skills/merc_magister/replenishing_touch.png"),
    ),
    (
        "merc_magister/reptillian_brain",
        include_bytes!("../../../assets/skills/merc_magister/reptillian_brain.png"),
    ),
    (
        "merc_magister/spellburn",
        include_bytes!("../../../assets/skills/merc_magister/spellburn.png"),
    ),
    (
        "merc_magister/tome_of_power",
        include_bytes!("../../../assets/skills/merc_magister/tome_of_power.png"),
    ),
    (
        "merc_magister/word_of_protection",
        include_bytes!("../../../assets/skills/merc_magister/word_of_protection.png"),
    ),
    (
        "merc_archer",
        include_bytes!("../../../assets/classes/merc_archer.png"),
    ),
    (
        "merc_knight",
        include_bytes!("../../../assets/classes/merc_knight.png"),
    ),
    (
        "merc_magister",
        include_bytes!("../../../assets/classes/merc_magister.png"),
    ),
];
